# NumPy

Project giving overview of NumPy, especially the numpy.random package

Author: Veronica Curry

Student ID: G00074924

****


This project includes the following:

> Overall Purpose of numpy.random

> Explaination of 'Simple Random Data' & 'Permutations'

> Use and Purpose of at least 5 'Distributions' functions

> The use of seeds in generating pseudorandom numbers


****


### NumPy

****

<div class="alert alert-block alert-info">
<b>Code:</b> 
    
    import numpy as np
    
</div>

NumPy is, at its most basic, numerical python.

It is a library that expands on the numerical capabilities of python and also acts as a basis for further numerical packages such as pandas or matplotlib [1]

NumPy's strength lies in it's abiliity to provide a step up from Python's lists, using arrays NumPy allows for easier, faster and more efficent manipulation of data. [2]

Arrays can be multi-dimensional or matrices. For a full overview of the many way in which arrays can be created and written please review this [page](https://medium.com/fintechexplained/why-should-we-use-numpy-c14a4fb03ee9) .[3]

As an extension of Python, NumPy is installed as part of Anaconda, and can be imported simply using an alias. [4] [5]


In [1]:
import numpy as np     # import the numpy package - this is the standard import abbreviation

This section of code will just provide a simple outline of the difference between lists and arrays. 

In the first sets of code you will clearly see the difference between simply adding two lists verses adding two arrays.

Lists will simply add the contents of both lists to a new list, where arrarys allow you to complete mathimatical processes on their contents. 

It should be noted that by using the append function we can also add the contents of an array to the contents of another array. Numpy offers you both options depending on your requirements. [6]

In [2]:
# Lists

list1 = [1,2,3]
list2 = [3,4,5]

list1 + list2

[1, 2, 3, 3, 4, 5]

In [3]:
# arrays

array1 = np.array([1,2,3])
array2 = np.array([3,4,5])

array1 + array2

array([4, 6, 8])

The differences and power of Numpy becomes more apparent when you multiply lists [7]

The code required to complete this action is much cleaner and simplier when using arrays. [8]

In [4]:
# Lists [8] 

list1 = [1,2,3]
list2 = [3,4,5]

listbylist = []
for i in range(0, len(list1)):
    listbylist.append(list1[i] * list2[i])

print("List1 multiplied by list2 is:" + str(listbylist))


List1 multiplied by list2 is:[3, 8, 15]


In [5]:
# arrays

array1 = np.array([1,2,3])
array2 = np.array([3,4,5])

array1 * array2

array([ 3,  8, 15])

These simple examples of code show the power of NumPy and the importance of the use of Arrays. 

From this viewpoint we can see how NumPy further builds to allow us greater capacity to generate numbers and use those numbers quickly and efficiently in programming, testing and Machine Learning.

*****

### NumPy Random

****

<div class="alert alert-block alert-info">
<b>Code:</b> 
   
    rng = np.random.default_rng()
    
</div>

NumPy provides a built-in function for random number generation – numpy.random [1]

This allows for the creation of pseudorandom data, in the forms of arrays, which can then be used in for mathematical problems, program testing, data Analysis etc. [2]

The provision of random data by NumPy allows us to learn programming and then importantly to test our programs with random, but also if required, reproducible data, prior to any real world application.

-----

<dl>
<dt>As outlined, in W3Schools it is important to remember:</dt>

<dd>“Random number does NOT mean a different number every time. Random means something that can not be predicted logically." </dd>[3]
    
-----

NumPy.random provides pseudorandom numbers for us to use – this means that the numbers are not totally random, infact NumPy.random gives us the ability to choose the kind of random numbers we need.

Pseudorandom data is data that is produced by Python, using an algorythim and by our imputs. It is not truly random and should not be treated as such. 

Numpy.random through the use of simple random data, permutations, and also number distributions allows us to amend and tailor the random data we need for our given purpose.[4]

Further we can actually choose the starting place for the random numbers we generate and reproduce the numbers through the use of seeds. [5] This allows for reproducible results for testing. 

In [13]:
rng = np.random.default_rng() # import the numpy package - this is the standard import abbreviation

~*~*~*~* more needed here

need to provide more explainationon the use of the above and it change in the newer docs
what does it mean?

No more seeds/

https://www.youtube.com/watch?v=ryvY3RJucag



----

### Simple Random Data & Permutations

----

When processing data we often want to give NumPy parameters as to what type of data we need, the permutations of this data and even as a further step the distibution of this data.

The first functions we can pass through Numpy.random are the following simple random data functions:

- integers
- random 
- choice
- bytes

~*~*~*~* more needed here


#### integers
                             
This function will output a list of random integers.
                             
                             rng.integers() 

This on its own will not work - for this function you are required to set parameters detailing the beginning and end numbers, the amount of numbers, shape of array, or boolean values. [2]

In [73]:
rng.integers(6, size=(2))       # here we set a highest value and the size of the output

array([2, 0], dtype=int64)

In [74]:
rng.integers(4,6, size=(2))     # here we have given a lowest value - highest value and then outlined the size of the output                          

array([4, 4], dtype=int64)

In [75]:
rng.integers(4,6, size=(2,4))  # here by changing the size parameters you can see we now have an array   


array([[4, 5, 4, 4],
       [4, 4, 4, 5]], dtype=int64)

In [84]:
rng.integers(4,6, size=(2,6,2))  # and very quickly we can create a multidimentional array


array([[[4, 4],
        [5, 4],
        [4, 5],
        [5, 5],
        [5, 4],
        [4, 5]],

       [[4, 4],
        [4, 4],
        [5, 4],
        [5, 5],
        [5, 4],
        [4, 5]]], dtype=int64)

In [85]:
rng.integers(4,6, size=(2,4)) 

array([[5, 5, 4, 5],
       [4, 4, 5, 5]], dtype=int64)

### References

#### NumPy
[1] Youtube, Amulya's Academy, Introduction to Numpy Library (13th Jul, 2019) https://www.youtube.com/watch?v=hSquw6JGsLM&list=PLzgPDYo_3xunqaoZnnTaoka2R6psn5u2T&index=194

[2] Youtube, I am biomed, What is Numpy? Python for Data Science Tutorial (16th April, 2016) https://www.youtube.com/watch?v=pP5dQG0foTs

[3] Medium, Farhad Malik, Why should we use NumpPy? (31st March, 2019) https://medium.com/fintechexplained/why-should-we-use-numpy-c14a4fb03ee9

[4] NumPy.org, Installing Numpy, (No Date)https://numpy.org/install/

[5] W3 Schools, Numpy Getting Started (1999 - 2021) https://www.w3schools.com/python/numpy/numpy_getting_started.asp

[6] Ask Python, How to append an Array in Python? (No Date) https://www.askpython.com/python/array/append-an-array-in-python

[7] Kite, How to multiply two lits in Python, (no date) https://www.kite.com/python/answers/how-to-multiply-two-lists-in-python

[8] Geeks for Geeks, Python - Multiply Two List (27th Dec, 2019) https://www.geeksforgeeks.org/python-multiply-two-list/

#### NumPy Random
[1] Great Learning, What is NumPy in Python, (28th May, 2021) https://www.mygreatlearning.com/blog/python-numpy-tutorial/ 

[2] Angela C, Explain the overall purpose of the package numpy.random (2021)
 https://www.angela1c.com/projects/numpy-random-files/task1/
 
[3] W3Schools, Random Numbers in NumPy, (1999 – 2021 ) https://www.w3schools.com/python/numpy/numpy_random.asp 

[4] NumPy, Random Generator, (22nd June, 2021) https://numpy.org/doc/stable/reference/random/generator.html#numpy.random.Generator 

[5] Towards Data Science, What does Random.seed do in NumPy, (27th Sept, 2021) https://towardsdatascience.com/random-seed-numpy-786cf7876a5f 


#### Simple Random Data & Permutations

[1] NumPy, Random Generator (22nd June, 2021) https://numpy.org/doc/stable/reference/random/generator.html#numpy.random.Generator

[2] Numpy, numpy.random.generator.integers (22nd June, 2021) https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.integers.html#numpy.random.Generator.integers

[3] Machine Learning Mastery, How to generate Random Numbers in Python (4th Sept, 2020)https://machinelearningmastery.com/how-to-generate-random-numbers-in-python/

[4] 
